"""add new tables

Revision ID: c41af6da8555
Revises: d1f7e55dab2b
Create Date: 2025-05-29 13:09:52.435009

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c41af6da8555"
down_revision = "d1f7e55dab2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ens_continuous_monitoring",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ens_id", sa.String(length=50), nullable=False),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("last_screened_time", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("name_international", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("postcode", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("phone_or_fax", sa.String(length=50), nullable=True),
        sa.Column("email_or_website", sa.String(length=100), nullable=True),
        sa.Column("national_id", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ens_id"),
    )
    op.create_table(
        "grid_PM_tracking",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("grid_tracking_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("grid_enquiry_id", sa.String(), nullable=True),
        sa.Column("primary_id", sa.String(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("grid_tracking_id"),
    )
    op.create_table(
        "management_association",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("grid_enquiry_id", sa.String(), nullable=True),
        sa.Column("primary_id", sa.String(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("contact_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("management_association")
    op.drop_table("grid_PM_tracking")
    op.drop_table("ens_continuous_monitoring")
    # ### end Alembic commands ###
