"""add columns to supplier_master_data

Revision ID: b7a3a0ee02f9
Revises: 45057a729c3f
Create Date: 2025-06-03 11:56:34.827240

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7a3a0ee02f9"
down_revision = "45057a729c3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(
        "supplier_master_data",
        sa.Column("uploaded_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "supplier_master_data",
        sa.Column("external_vendor_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
