"""changes

Revision ID: 2350d8bc681f
Revises: c41af6da8555
Create Date: 2025-05-29 15:15:25.169676

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2350d8bc681f"
down_revision = "c41af6da8555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ens_continuous_monitoring",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "grid_PM_tracking",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.add_column(
        "management_association", sa.Column("name", sa.String(), nullable=True)
    )
    op.add_column(
        "management_association",
        sa.Column("associated_ens_id", sa.String(), nullable=True),
    )
    op.alter_column(
        "management_association",
        "contact_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("management_association", "grid_enquiry_id")
    op.drop_column("management_association", "primary_id")
    op.drop_column("management_association", "category")
    op.alter_column(
        "webhook_response",
        "response",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.String(length=50),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_response",
        "response",
        existing_type=sa.String(length=50),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.add_column(
        "management_association",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "management_association",
        sa.Column("primary_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "management_association",
        sa.Column("grid_enquiry_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "management_association",
        "contact_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("management_association", "associated_ens_id")
    op.drop_column("management_association", "name")
    op.alter_column(
        "grid_PM_tracking",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "ens_continuous_monitoring",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
