"""reenable_pk

Revision ID: f71c3048e00f
Revises: 2350d8bc681f
Create Date: 2025-05-29 15:57:03.931754

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f71c3048e00f"
down_revision = "2350d8bc681f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('management_association_pkey', 'management_association', type_='primary')

    op.alter_column(
        "management_association",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True
    )

    op.create_primary_key(
        'management_association_pkey', 'management_association', ['contact_id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('management_association_pkey', 'management_association', type_='primary')

    op.alter_column(
        "management_association",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True
    )

    op.create_primary_key(
        'management_association_pkey', 'management_association', ['id']
    )
    # ### end Alembic commands ###
